package aa.exception.handling_rules;

public class Test01{
	
	public static void main(String []args ) {
		
		try  { }
		catch(){}
		finally {};
   	}
	
}