package aa.exceptionhandlinh_calling_propogetion;

public class Test02TryCatch {

}
